In [1]:
import numpy as np

In [2]:

# ==========================================================
# 1. ARRAY CREATION
# ==========================================================
print("ARRAY CREATION")
print(np.array([1,2,3]))              
print(np.asarray([4,5,6]))           
print(np.arange(0,10,2))                 
print(np.linspace(0,1,5))              
print(np.logspace(1,3,3))              
print(np.geomspace(1,1000,4))           
print(np.zeros((2,3)))                   # zeros
print(np.ones((2,3)))                    # ones
print(np.empty((2,3)))                   # empty
print(np.full((2,3),7))                  # full
print(np.identity(3))                    # identity
print(np.eye(3,4,k=1))                   # eye with shift
print(np.diag([1,2,3]))                  # diagonal
print(np.tri(3))                         # lower triangle
print(np.tril([[1,2],[3,4]]))            # lower part
print(np.triu([[1,2],[3,4]]))            # upper part
print(np.meshgrid([1,2],[3,4]))          # meshgrid
print(np.fromfunction(lambda i,j: i+j,(2,3),dtype=int))
print(np.fromiter(range(5),dtype=int))
print(np.indices((2,3)))

ARRAY CREATION
[1 2 3]
[4 5 6]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  10.  100. 1000.]
[   1.   10.  100. 1000.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[1 0]
 [3 4]]
[[1 2]
 [0 4]]
(array([[1, 2],
       [1, 2]]), array([[3, 3],
       [4, 4]]))
[[0 1 2]
 [1 2 3]]
[0 1 2 3 4]
[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


In [3]:

# Random arrays
print(np.random.rand(2,3))
print(np.random.randn(2,3))
print(np.random.randint(1,10,(2,3)))
print(np.random.random_sample((2,2)))
print(np.random.choice([1,2,3],5))
arr = np.arange(5)
np.random.shuffle(arr)
print(arr)
print(np.random.permutation([1,2,3,4]))

[[0.13219149 0.74724986 0.77555768]
 [0.51547425 0.88059183 0.05146459]]
[[-0.74512471 -0.19450348 -1.65074369]
 [ 0.96041551 -0.68284158  0.10284538]]
[[6 7 4]
 [7 9 3]]
[[0.1670672  0.66128846]
 [0.51193331 0.31272436]]
[1 3 2 3 2]
[0 3 1 2 4]
[4 3 2 1]


In [4]:

# ==========================================================
# 2. ARRAY ATTRIBUTES & INSPECTION
# ==========================================================
print("\nARRAY ATTRIBUTES")
a = np.array([[1,2,3],[4,5,6]])
print(a.shape, a.ndim, a.size, a.dtype, a.itemsize, a.nbytes)
print(np.isscalar(5), np.iscomplex([1+2j,3]))
print(np.isreal([1+2j,3]))
print(np.isfinite([1,np.inf,np.nan]))


ARRAY ATTRIBUTES
(2, 3) 2 6 int64 8 48
True [ True False]
[False  True]
[ True False False]


In [ ]:
# ==========================================================
# 3. INDEXING & SLICING
# ==========================================================
print("\nINDEXING & SLICING")
b = np.arange(10)
print(b[2])
print(b[2:7])
print(b[::-1])
print(b[[1,3,5]])
print(b[b%2==0])
print(np.take(b,[1,4,7]))
c = np.array([10,20,30,40])
np.put(c,[0,2],[99,77])
print(c)
print(np.choose([0,1,0],[ [1,2,3],[4,5,6] ]))
print(np.where(b>5))
print(np.nonzero(b))
print(np.argwhere(b>5))
print(np.compress([0,1,0,1],c))


INDEXING & SLICING
2
[2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5]
[0 2 4 6 8]
[1 4 7]
[99 20 77 40]
[1 5 3]
(array([6, 7, 8, 9]),)
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)
[[6]
 [7]
 [8]
 [9]]
[20 40]


In [6]:


# ==========================================================
# 4. ARRAY MANIPULATION
# ==========================================================
print("\nARRAY MANIPULATION")
d = np.arange(6)
print(d.reshape(2,3))
print(d.ravel())
print(d.flatten())
print(np.squeeze([[1],[2],[3]]))
print(np.transpose([[1,2,3],[4,5,6]]))
print(np.swapaxes([[1,2],[3,4]],0,1))
print(np.moveaxis(np.ones((1,2,3)),0,-1).shape)
print(np.concatenate([d,d]))
print(np.stack([d,d]))
print(np.hstack([d,d]))
print(np.vstack([d,d]))
print(np.dstack([d,d]))
print(np.column_stack(([1,2,3],[4,5,6])))
print(np.row_stack(([1,2,3],[4,5,6])))
print(np.split(d,3))
print(np.hsplit(np.arange(12).reshape(2,6),3))
print(np.vsplit(np.arange(12).reshape(6,2),3))
print(np.tile([1,2],3))
print(np.repeat([1,2],3))


ARRAY MANIPULATION
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[1 2 3]
[[1 4]
 [2 5]
 [3 6]]
[[1 3]
 [2 4]]
(2, 3, 1)
[0 1 2 3 4 5 0 1 2 3 4 5]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[0 1 2 3 4 5 0 1 2 3 4 5]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[array([0, 1]), array([2, 3]), array([4, 5])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]])]
[1 2 1 2 1 2]
[1 1 1 2 2 2]


C:\Users\Ajinkya\AppData\Local\Temp\ipykernel_10156\74123089.py:19: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack(([1,2,3],[4,5,6])))


In [7]:




# ==========================================================
# 5. MATHEMATICAL OPERATIONS
# ==========================================================
print("\nMATH OPERATIONS")
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y, x-y, x*y, x/y)
print(np.add(x,y), np.subtract(x,y))
print(np.multiply(x,y), np.divide(y,x))
print(np.mod(y,x))
print(np.power(x,2))
print(np.reciprocal([1,2,3]))
print(np.sin(x), np.cos(x), np.tan(x))
print(np.arcsin([0,1]))
print(np.sinh([0,1]))
print(np.floor([1.7,-1.7]))
print(np.ceil([1.2,-1.2]))
print(np.trunc([1.5,-1.5]))
print(np.rint([1.5,2.5]))
print(np.fix([1.5,-1.5]))
print(np.exp([1,2]))
print(np.expm1([1,2]))
print(np.log([1,np.e,np.e**2]))
print(np.log10([1,10,100]))
print(np.log2([1,2,4]))
print(np.log1p([0,1]))
print(np.sqrt([1,4,9]))
print(np.cbrt([1,8,27]))
print(np.square([2,3]))
print(np.abs([-1,2,-3]))
print(np.sign([-10,0,10]))
print(np.clip([-5,0,5],-1,1))


MATH OPERATIONS
[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]
[5 7 9] [-3 -3 -3]
[ 4 10 18] [4.  2.5 2. ]
[0 1 0]
[1 4 9]
[1 0 0]
[0.84147098 0.90929743 0.14112001] [ 0.54030231 -0.41614684 -0.9899925 ] [ 1.55740772 -2.18503986 -0.14254654]
[0.         1.57079633]
[0.         1.17520119]
[ 1. -2.]
[ 2. -1.]
[ 1. -1.]
[2. 2.]
[ 1. -1.]
[2.71828183 7.3890561 ]
[1.71828183 6.3890561 ]
[0. 1. 2.]
[0. 1. 2.]
[0. 1. 2.]
[0.         0.69314718]
[1. 2. 3.]
[1. 2. 3.]
[4 9]
[1 2 3]
[-1  0  1]
[-1  0  1]


In [8]:


# ==========================================================
# 6. AGGREGATE / STATISTICS
# ==========================================================
print("\nAGGREGATES")
m = np.array([[1,2,3],[4,5,6]])
print(m.sum(), m.prod())
print(m.mean(), m.std(), m.var())
print(m.min(), m.max(), np.ptp(m))
print(m.argmin(), m.argmax())
print(m.cumsum(), m.cumprod())
print(np.median(m), np.percentile(m,50))
print(np.quantile(m,0.25))



AGGREGATES
21 720
3.5 1.707825127659933 2.9166666666666665
1 6 5
0 5
[ 1  3  6 10 15 21] [  1   2   6  24 120 720]
3.5 3.5
2.25


In [9]:

# ==========================================================
# 7. LINEAR ALGEBRA
# ==========================================================
print("\nLINEAR ALGEBRA")
p = np.array([[1,2],[3,4]])
q = np.array([[5,6],[7,8]])
print(np.dot(p,q))
print(np.matmul(p,q))
print(np.vdot([1,2,3],[4,5,6]))
print(np.inner([1,2],[3,4]))
print(np.outer([1,2],[3,4]))
print(np.cross([1,2,3],[4,5,6]))
print(np.tensordot([1,2],[3,4],axes=1))
print(np.linalg.det(p))
print(np.linalg.inv(p))
print(np.linalg.eig(p))
print(np.linalg.eigvals(p))
print(np.linalg.svd(p))
print(np.linalg.qr(p))
print(np.linalg.cholesky([[1,0],[0,1]]))
print(np.linalg.solve(p,[5,6]))
print(np.linalg.lstsq(p,[5,6],rcond=None))
print(np.linalg.matrix_power(p,2))
print(np.linalg.matrix_rank(p))
print(np.linalg.norm([3,4]))
print(np.linalg.cond(p))


LINEAR ALGEBRA
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
32
11
[[3 4]
 [6 8]]
[-3  6 -3]
11
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[-0.37228132  5.37228132]
SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), R=array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))
[[1. 0.]
 [0. 1.]]
[-4.   4.5]
(array([-4. ,  4.5]), array([], dtype=float64), np.int32(2), array([5.4649857 , 0.36596619]))
[[ 7 10]
 [15 22]]
2
5.0
14.933034373659268


In [10]:


# ==========================================================
# 8. RANDOM (more distributions)
# ==========================================================
print("\nRANDOM DISTRIBUTIONS")
print(np.random.binomial(10,0.5,5))
print(np.random.poisson(5,5))
print(np.random.normal(0,1,5))
print(np.random.uniform(0,1,5))
print(np.random.beta(2,5,5))
print(np.random.gamma(2,2,5))
print(np.random.chisquare(2,5))
print(np.random.exponential(1,5))
print(np.random.laplace(0,1,5))
print(np.random.logistic(0,1,5))
print(np.random.multinomial(10,[0.2,0.8]))
print(np.random.multivariate_normal([0,0],[[1,0],[0,1]],2))
print(np.random.pareto(1,5))
print(np.random.zipf(2,5))



RANDOM DISTRIBUTIONS
[3 5 6 6 5]
[4 4 6 4 3]
[-0.59912898  0.55903517 -0.04591143 -1.31411807 -0.51990332]
[0.19366774 0.96083843 0.95421749 0.52725343 0.55584466]
[0.63473786 0.23366586 0.21138956 0.06237841 0.1148867 ]
[9.47610661 3.09936547 4.00768885 5.40892922 1.22128981]
[0.10167973 1.27721536 3.62108821 4.2863949  0.11762672]
[0.74744696 2.13312975 0.04150701 1.7751704  0.30675143]
[ 0.05594684  2.79736516  0.60977642  0.19790191 -0.88005278]
[ 0.18164691 -0.10839228 -2.75334446  2.21583548 -3.5942771 ]
[ 0 10]
[[1.47825248 0.82603841]
 [0.65039168 1.23515412]]
[0.25883098 8.32050306 0.07754318 1.44698334 6.03126817]
[1 1 2 1 1]


In [11]:

# ==========================================================
# 9. SORTING & SET OPS
# ==========================================================
print("\nSORTING & SET OPS")
s = np.array([5,2,9,1])
print(np.sort(s))
print(np.argsort(s))
print(np.lexsort((s,)))
print(np.partition(s,2))
print(np.argpartition(s,2))
print(np.searchsorted([1,2,3,4,5],3))
print(np.unique([1,2,2,3]))
print(np.intersect1d([1,2,3],[2,3,4]))
print(np.union1d([1,2],[2,3]))
print(np.setdiff1d([1,2,3],[3,4]))
print(np.setxor1d([1,2,3],[2,3,4]))
print(np.in1d([1,2,3],[2,4]))


SORTING & SET OPS
[1 2 5 9]
[3 1 0 2]
[3 1 0 2]
[1 2 5 9]
[3 1 0 2]
2
[1 2 3]
[2 3]
[1 2 3]
[1 2]
[1 4]
[False  True False]


C:\Users\Ajinkya\AppData\Local\Temp\ipykernel_10156\4283673129.py:17: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d([1,2,3],[2,4]))


In [12]:


# ==========================================================
# 10. FILE I/O
# ==========================================================
print("\nFILE I/O")
np.savetxt("data.txt", np.array([1,2,3]))
print(np.loadtxt("data.txt"))



FILE I/O
[1. 2. 3.]


In [13]:

# ==========================================================
# 11. SPECIAL FUNCTIONS
# ==========================================================
print("\nSPECIAL FUNCTIONS")
print(np.meshgrid([1,2],[3,4]))
print(np.ogrid[0:3,0:3])
print(np.mgrid[0:3,0:3])
print(np.diagflat([1,2,3]))
print(np.histogram([1,2,1,2,3],bins=3))
print(np.histogram2d([1,2,1],[1,2,2],bins=2))
print(np.digitize([0.2,6.4,3.0,1.6],bins=[0,1,3,5,7]))
print(np.bincount([0,1,1,2,2,2]))


SPECIAL FUNCTIONS
(array([[1, 2],
       [1, 2]]), array([[3, 3],
       [4, 4]]))
(array([[0],
       [1],
       [2]]), array([[0, 1, 2]]))
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
(array([2, 2, 1]), array([1.        , 1.66666667, 2.33333333, 3.        ]))
(array([[1., 1.],
       [0., 1.]]), array([1. , 1.5, 2. ]), array([1. , 1.5, 2. ]))
[1 4 3 2]
[1 2 3]
