In [2]:
import numpy as np

print(np.array([1,2,3]))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.empty((2,3)))
print(np.full((2,3),7))
print(np.identity(3))
print(np.eye(3,4,k=1))
print(np.diag([1,2,3]))
print(np.random.rand(2,3))
print(np.random.randint(1,10,(2,3)))


[1 2 3]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0.50050625 0.47864469 0.18684596]
 [0.62083518 0.24167801 0.02789151]]
[[2 4 8]
 [2 4 9]]


In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


(2, 3)
2
6
int64
8
48


In [3]:
a = np.arange(10)
print(a[2])
print(a[2:7])
print(a[::-1])
print(a[[1,3,5]])
print(a[a%2==0])


2
[2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5]
[0 2 4 6 8]


In [4]:
b = np.arange(6)
print(b.reshape(2,3))
print(b.ravel())
print(b.reshape(2,3).T)
print(np.concatenate([b,b]))
print(np.stack([b,b]))


[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]
[0 1 2 3 4 5 0 1 2 3 4 5]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [5]:
m = np.array([[1,2,3],[4,5,6]])
print(m.sum())
print(m.mean())
print(m.std())
print(m.min(), m.max())
print(m.argmin(), m.argmax())
print(m.cumsum())
print(m.cumprod())


21
3.5
1.707825127659933
1 6
0 5
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]


In [3]:
import numpy as np

arr = np.array([1, 2, 3])
print(np.repeat(arr, 4))
print(np.repeat(arr, [1, 2, 3]))

arr2 = np.array([[1, 2], [3, 4]])
print(np.repeat(arr2, 2, axis=0))
print(np.repeat(arr2, 2, axis=1))


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(np.hsplit(arr, 2))
print(np.hsplit(arr, [1, 3]))


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(np.vsplit(arr, 2))
print(np.vsplit(arr, [1, 3]))


[1 1 1 1 2 2 2 2 3 3 3 3]
[1 2 2 3 3 3]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[[1 1 2 2]
 [3 3 4 4]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1],
       [5]]), array([[2, 3],
       [6, 7]]), array([[4],
       [8]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


In [ ]:
arr=np.copy()

arr=np.view()
arr=np.clip(arr, 3, 8)
arr=np.where(arr > 5, arr, 0)
arr=np.unique(arr)
np.rand()
print(arr.T)
np.shuffle(arr)
np.sort(arr)
np.permutation(arr)
np.argmax(arr)
np.argmin(arr)
np.dot(arr)

TypeError: copy() missing 1 required positional argument: 'a'