In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])         # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (matrix)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D array


In [4]:
np.zeros((3, 4))      # 3x4 array of zeros
np.ones((2, 3))       # 2x3 array of ones
np.full((2, 2), 7)    # 2x2 array filled with 7
print(np.eye(4)   )          # 4x4 identity matrix
np.empty((3, 3))      # uninitialized array (random values)
print(np.identity(3))  # 3x3 identity matrix


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)  # 5 numbers between 0 and 1


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
np.random.rand(2, 3)       # 2x3 array of random floats [0,1)
np.random.randn(2, 3)      # normal distribution (mean=0, var=1)
np.random.randint(1, 10, (2, 3))  # random integers between 1 and 9


array([[7, 9, 4],
       [5, 7, 6]], dtype=int32)

In [5]:
arr = np.arange(12)       # [0, 1, 2, ..., 11]
arr.shape                 # (12,)
arr.reshape(3, 4)         # reshape to 3x4
arr.reshape(2, 2, 3)      # reshape to 3D


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [6]:
arr.reshape(3, 4).flatten()  # convert to 1D copy
arr.reshape(3, 4).ravel()    # convert to 1D view (no copy)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.T                        # transpose
np.swapaxes(mat, 0, 1)       # swap rows and columns


array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))          # [1, 2, 3, 4, 5, 6]
np.vstack((a, b))               # stack vertically
np.hstack((a, b))               # stack horizontally
np.dstack((a, b))               # stack depth-wise (3D)


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [9]:
arr = np.arange(10)
np.split(arr, 5)          # split into 5 equal arrays
np.array_split(arr, 3)    # split into 3 (not always equal)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [10]:
arr = np.arange(10)
np.split(arr, 5)          # split into 5 equal arrays
np.array_split(arr, 3)    # split into 3 (not always equal)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [11]:
arr = np.array([1, 2, 3, 4, 5])

np.append(arr, [6, 7])           # add at end
np.insert(arr, 2, 99)            # insert 99 at index 2
np.delete(arr, [1, 3])           # delete elements at index 1 and 3


array([1, 3, 5])

In [12]:
a = np.array([1, 2, 3])
b = a.copy()      # independent copy
c = a.view()      # shares same data
a[0] = 99
# b is unchanged, c changes


In [13]:
arr = np.array([3, 1, 2, 5, 4])
np.sort(arr)                      # [1,2,3,4,5]

mat = np.array([[3, 2, 1], [6, 5, 4]])
np.sort(mat, axis=0)              # sort by column
np.sort(mat, axis=1)              # sort by row


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # first element → 10
print(arr[-1])   # last element  → 50
print(arr[2])    # third element → 30


10
50
30


In [15]:
print(arr[1:4])     # elements from index 1 to 3 → [20, 30, 40]
print(arr[:3])      # from start to index 2 → [10, 20, 30]
print(arr[2:])      # from index 2 to end → [30, 40, 50]
print(arr[::2])     # every 2nd element → [10, 30, 50]


[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


In [16]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(mat[0, 0])   # element at row 0, col 0 → 1
print(mat[1, 2])   # element at row 1, col 2 → 6
print(mat[-1, -1]) # last row, last col → 9


1
6
9


In [17]:
print(mat[0:2, 1:3])   # rows 0-1, cols 1-2 → [[2, 3],[5, 6]]
print(mat[:, 1])       # all rows, col 1 → [2, 5, 8]
print(mat[1, :])       # row 1, all cols → [4, 5, 6]


[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]


In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])   # pick elements at index 0, 2, 4 → [10, 30, 50]


[10 30 50]


In [19]:
mat = np.array([[10, 20], [30, 40], [50, 60]])
print(mat[[0, 2], [1, 0]])  # picks (0,1) → 20 and (2,0) → 50


[20 50]


In [20]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])      # [30, 40, 50]
print(arr[arr % 20 == 0]) # [20, 40]


[30 40 50]
[20 40]


In [21]:
arr = np.array([10, 20, 30, 40, 50])
print(np.where(arr > 25))    # indices where condition is true → (array([2, 3, 4]),)


(array([2, 3, 4]),)
