In [1]:
import numpy as np



In [ ]:
a = np.array([1, 2, 3])
print("array:", a)

b = np.asarray([4, 5, 6])
print("asarray:", b)

z = np.zeros((2,3))
print("zeros:\n", z)


o = np.ones((2,2))
print("ones:\n", o)

e = np.empty((2,2))
print("empty:\n", e)

f = np.full((2,3), 7)
print("full:\n", f)


ar = np.arange(0, 10, 2)
print("arange:", ar)

ls = np.linspace(0, 1, 5)
print("linspace:", ls)

# eye
eye = np.eye(3)
print("eye:\n", eye)


iden = np.identity(4)
print("identity:\n", iden)


array: [1 2 3]
asarray: [4 5 6]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]]
empty:
 [[1. 1.]
 [1. 1.]]
full:
 [[7 7 7]
 [7 7 7]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print("ndim:", a.ndim)    
print("shape:", a.shape)  
print("size:", a.size)    
print("dtype:", a.dtype)  


ndim: 2
shape: (2, 3)
size: 6
dtype: int64


In [ ]:
a = np.array([1.7, 2.8, 3.9])
print("astype:", a.astype(int))   

b = np.array([10,20,30])
print("tolist:", b.tolist())      


astype: [1 2 3]
tolist: [10, 20, 30]


In [ ]:
a = np.arange(6)
print("reshape:\n", a.reshape(2,3))

print("ravel:", a.ravel())    # [0 1 2 3 4 5]

print("flatten:", a.flatten())  # [0 1 2 3 4 5]

b = np.array([[1,2],[3,4]])
print("transpose:\n", b.transpose())
# [[1 3]
#  [2 4]]

c = np.array([[[1],[2],[3]]])
print("squeeze:", np.squeeze(c))  # [1 2 3]

d = np.array([1,2])
print("expand_dims:", np.expand_dims(d, axis=0))  
# [[1 2]]

x = np.array([1,2])
y = np.array([3,4])
print("concatenate:", np.concatenate((x,y)))  # [1 2 3 4]

print("stack:\n", np.stack((x,y)))
# [[1 2]
#  [3 4]]

print("hstack:", np.hstack((x,y)))  # [1 2 3 4]

print("vstack:\n", np.vstack((x,y)))
# [[1 2]
#  [3 4]]

arr = np.arange(6)
print("split:", np.split(arr, 3))  
# [array([0, 1]), array([2, 3]), array([4, 5])]


reshape:
 [[0 1 2]
 [3 4 5]]
ravel: [0 1 2 3 4 5]
flatten: [0 1 2 3 4 5]
transpose:
 [[1 3]
 [2 4]]
squeeze: [1 2 3]
expand_dims: [[1 2]]
concatenate: [1 2 3 4]
stack:
 [[1 2]
 [3 4]]
hstack: [1 2 3 4]
vstack:
 [[1 2]
 [3 4]]
split: [array([0, 1]), array([2, 3]), array([4, 5])]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("add:", np.add(a,b))          # [5 7 9]
print("subtract:", np.subtract(a,b))# [-3 -3 -3]
print("multiply:", np.multiply(a,b))# [ 4 10 18]
print("divide:", np.divide(b,a))    # [4.  2.5 2. ]
print("mod:", np.mod(b,a))          # [0 1 0]
print("power:", np.power(a,2))      # [1 4 9]
print("negative:", np.negative(a))  # [-1 -2 -3]


add: [5 7 9]
subtract: [-3 -3 -3]
multiply: [ 4 10 18]
divide: [4.  2.5 2. ]
mod: [0 1 0]
power: [1 4 9]
negative: [-1 -2 -3]


In [7]:
a = np.array([1,2,3,4,5])

print("min:", np.min(a))      # 1
print("max:", np.max(a))      # 5
print("argmin:", np.argmin(a))# 0
print("argmax:", np.argmax(a))# 4
print("mean:", np.mean(a))    # 3.0
print("median:", np.median(a))# 3.0
print("std:", np.std(a))      # 1.4142
print("var:", np.var(a))      # 2.0
print("sum:", np.sum(a))      # 15
print("prod:", np.prod(a))    # 120
print("cumsum:", np.cumsum(a))# [ 1  3  6 10 15]
print("cumprod:", np.cumprod(a))# [  1   2   6  24 120]


min: 1
max: 5
argmin: 0
argmax: 4
mean: 3.0
median: 3.0
std: 1.4142135623730951
var: 2.0
sum: 15
prod: 120
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


In [8]:
a = np.array([3,1,2])
print("sort:", np.sort(a))        # [1 2 3]

print("argsort:", np.argsort(a))  # [1 2 0]

b = np.array([1,2,2,3,3,3])
print("unique:", np.unique(b))    # [1 2 3]


sort: [1 2 3]
argsort: [1 2 0]
unique: [1 2 3]


In [ ]:
print("rand:", np.random.rand(2,2))
# e.g. [[0.55 0.71]
#       [0.42 0.99]]

print("randint:", np.random.randint(1,10,5))  
# e.g. [3 7 4 6 1]

print("choice:", np.random.choice([10,20,30], 5))  
# e.g. [30 10 20 10 30]

arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print("shuffle:", arr) 

np.random.seed(0)
print("seed + rand:", np.random.rand(3))


rand: [[0.22914398 0.85285527]
 [0.10614987 0.63682326]]
randint: [7 3 6 8 7]
choice: [10 20 30 30 10]
shuffle: [1 5 3 4 2]
seed + rand: [0.5488135  0.71518937 0.60276338]
